--go
--use master 
--if exists (select name from sys.databases where name = 'QLCD')
drop database PawnShop
go
create database PawnShop
go 
use PawnShop
go
drop table LOAIMATHANG
GO
CREATE TABLE LOAIMATHANG
(
	MALOAI varchar(10) PRIMARY KEY,
	TENLOAI NVARCHAR(50),
)
go
drop table MATHANG
GO
CREATE TABLE MATHANG
(
	MAMATHANG varchar(10) PRIMARY KEY,
	TENMATHANG NVARCHAR(50),
	MALOAI varchar(10),
	TT_MH BIT,
	foreign key (MALOAI) references LOAIMATHANG(MALOAI) on update cascade 
)
GO
drop table KHACHHANG
GO
CREATE TABLE KHACHHANG
(
	MAKHACHHANG varchar(10) PRIMARY KEY,
	TENKHACHHANG NVARCHAR(50),
	SDT VARCHAR(10) CHECK (DATALENGTH([SDT]) = 10) ,
	DIACHI NVARCHAR(100),	
	CMND VARCHAR(12) UNIQUE check (DATALENGTH([CMND]) = 12),
	TT_KH bit
)
GO
drop table TAIKHOAN
GO
CREATE TABLE TAIKHOAN
(
	TEN_TAI_KHOAN VARCHAR(20) PRIMARY KEY,
	MAT_KHAU VARCHAR(20),
	HO_VA_TEN_USER NVARCHAR(30)
)
GO
drop table PHIEUCAMDO
GO
CREATE TABLE PHIEUCAMDO
(
	MAPHIEU varchar(10) PRIMARY KEY,
	NGAYLAP DATETIME,
	TIENTRA FLOAT,
	TRANGTHAI bit,
	MAKHACHHANG varchar(10),
	TEN_TAI_KHOAN VARCHAR(20),
	TT_PCD bit,
	foreign key (MAKHACHHANG) references KHACHHANG(MAKHACHHANG) on update cascade,
	foreign key (TEN_TAI_KHOAN) references TAIKHOAN(TEN_TAI_KHOAN) on update cascade,
)
GO
drop table CTPHIEUCAMDO
GO
CREATE TABLE CTPHIEUCAMDO
(
	MAMATHANG varchar(10),
	MAPHIEU varchar(10),
	SOLUONG int,
	TIENCAM money,
	NGAYDONGLAI DATETIME,
	TT_CTPCD bit,
	PRIMARY KEY (MAMATHANG,MAPHIEU),
	foreign key (MAMATHANG) references MATHANG(MAMATHANG) on update cascade,
	foreign key (MAPHIEU) references PHIEUCAMDO(MAPHIEU) on update cascade
)
GO 
drop table PHIEUTHANHTOAN
GO
CREATE TABLE PHIEUTHANHTOAN
(
	MAPHIEUTHANHTOAN varchar(10) PRIMARY KEY,
	NGAYLAPPHIEUTHANHTOAN DATETIME,
	MAPHIEU varchar(10),
	TIENLAI FLOAT,
	TONGTIEN MONEY,
	TT_PTT bit,
	foreign key (MAPHIEU) references PHIEUCAMDO(MAPHIEU) on update cascade 
)
GO
SET DATEFORMAT DMY