/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.StaticUser;
import Support.MessageSupport;
import Support.Support;
import View.JTabbedPaneForm.AccountJPanelForm;
import View.JTabbedPaneForm.CustomerJPanelForm;
import View.JTabbedPaneForm.PawnCouponJPanelForm;
import View.JTabbedPaneForm.ProductJPanelForm;
import View.JTabbedPaneForm.ProfileJPanelForm;
import View.JTabbedPaneForm.StatisticJPanelForm;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NVS
 */
@SuppressWarnings("ClassWithoutLogger")
public class HomePageJFrameForm extends javax.swing.JFrame {

    private static HomePageJFrameForm instance;

    public static HomePageJFrameForm getCurrentInstance() {
        if (instance == null) {
            instance = new HomePageJFrameForm();
        }
        return instance;
    }

    private static final long serialVersionUID = 1L;

    private static JFrame jfparrent = null;
    private JPanel jaccounttab = null;
    private JPanel jprofiletab = null;
    private JPanel jcustomertab = null;
    private JPanel jproducttab = null;
    private JPanel jpawncoupontab = null;
    private JPanel jstatistictab = null;

    public HomePageJFrameForm() {
        initComponents();
    }

    @SuppressWarnings({"static-access", "OverridableMethodCallInConstructor", "SleepWhileInLoop"})
    public HomePageJFrameForm(JFrame jfparrent) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/logo.png")));
        this.jfparrent = jfparrent;
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Support.ScaleImage(jlbHomePage, getClass().getResource("/Image/HomePage/HomePageImage6.png"));
        @SuppressWarnings("CollectionWithoutInitialCapacity")
        List<URL> imagesList = new ArrayList<>();
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage0.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage1.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage2.jpg"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage3.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage4.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage5.jpg"));
        Support.setSlideImage(jlbHomePage, imagesList);

        Support.getClock(jlblClock, true);
        jlblProfile.setText(StaticUser.getCurrentInstance().getFullname());
        jmiAccount.setVisible(StaticUser.getCurrentInstance().getUsername().equals("admin"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jHomePagePanel = new javax.swing.JPanel();
        jFooterPanel = new javax.swing.JPanel();
        jlbToday = new javax.swing.JLabel();
        jlblClock = new javax.swing.JLabel();
        jAccountNamePanel = new javax.swing.JPanel();
        jlblProfile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtpHomePage = new javax.swing.JTabbedPane();
        jlbHomePage = new javax.swing.JLabel();
        jHeaderMenuBar = new javax.swing.JMenuBar();
        jmSystem = new javax.swing.JMenu();
        jmiLogOut = new javax.swing.JMenuItem();
        jmManagerment = new javax.swing.JMenu();
        jmiAccount = new javax.swing.JMenuItem();
        jmiCustomer = new javax.swing.JMenuItem();
        jmiProduct = new javax.swing.JMenuItem();
        jmiPawnCoupon = new javax.swing.JMenuItem();
        jmStatistic = new javax.swing.JMenu();
        jmiStatistic = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm quản lý cầm dùm đồ");
        setBackground(new java.awt.Color(102, 102, 102));

        jHomePagePanel.setBackground(new java.awt.Color(0, 255, 255));
        jHomePagePanel.setForeground(new java.awt.Color(255, 255, 255));

        jFooterPanel.setBackground(new java.awt.Color(0, 255, 255));
        jFooterPanel.setForeground(new java.awt.Color(0, 0, 0));

        jlbToday.setBackground(new java.awt.Color(204, 204, 204));
        jlbToday.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbToday.setForeground(new java.awt.Color(255, 0, 0));
        jlbToday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbToday.setText("Hôm nay :");
        jlbToday.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jlblClock.setBackground(new java.awt.Color(204, 204, 204));
        jlblClock.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblClock.setForeground(new java.awt.Color(255, 0, 0));
        jlblClock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblClock.setText("Clock");
        jlblClock.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jAccountNamePanel.setBackground(new java.awt.Color(0, 255, 255));
        jAccountNamePanel.setForeground(new java.awt.Color(0, 0, 0));

        jlblProfile.setBackground(new java.awt.Color(255, 255, 255));
        jlblProfile.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jlblProfile.setForeground(new java.awt.Color(255, 0, 0));
        jlblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblProfile.setText("Họ và tên");
        jlblProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlblProfileMouseMoved(evt);
            }
        });
        jlblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblProfileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblProfileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jAccountNamePanelLayout = new javax.swing.GroupLayout(jAccountNamePanel);
        jAccountNamePanel.setLayout(jAccountNamePanelLayout);
        jAccountNamePanelLayout.setHorizontalGroup(
            jAccountNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAccountNamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblProfile)
                .addContainerGap())
        );
        jAccountNamePanelLayout.setVerticalGroup(
            jAccountNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFooterPanelLayout = new javax.swing.GroupLayout(jFooterPanel);
        jFooterPanel.setLayout(jFooterPanelLayout);
        jFooterPanelLayout.setHorizontalGroup(
            jFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFooterPanelLayout.createSequentialGroup()
                .addComponent(jlbToday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAccountNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFooterPanelLayout.setVerticalGroup(
            jFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAccountNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbToday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtpHomePage.setBackground(new java.awt.Color(204, 204, 204));
        jtpHomePage.setForeground(new java.awt.Color(0, 0, 0));
        jtpHomePage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jtpHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));
        jPanel1.add(jlbHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 1270, 600));

        javax.swing.GroupLayout jHomePagePanelLayout = new javax.swing.GroupLayout(jHomePagePanel);
        jHomePagePanel.setLayout(jHomePagePanelLayout);
        jHomePagePanelLayout.setHorizontalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHomePagePanelLayout.setVerticalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePagePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jHeaderMenuBar.setBackground(new java.awt.Color(153, 153, 153));
        jHeaderMenuBar.setForeground(new java.awt.Color(0, 0, 0));
        jHeaderMenuBar.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jmSystem.setBackground(new java.awt.Color(153, 153, 153));
        jmSystem.setForeground(new java.awt.Color(0, 0, 0));
        jmSystem.setText("Hệ thống");

        jmiLogOut.setBackground(new java.awt.Color(204, 204, 204));
        jmiLogOut.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiLogOut.setForeground(new java.awt.Color(0, 0, 0));
        jmiLogOut.setText("Đăng xuất");
        jmiLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOutActionPerformed(evt);
            }
        });
        jmSystem.add(jmiLogOut);

        jHeaderMenuBar.add(jmSystem);

        jmManagerment.setBackground(new java.awt.Color(153, 153, 153));
        jmManagerment.setForeground(new java.awt.Color(0, 0, 0));
        jmManagerment.setText("Quản lý");

        jmiAccount.setBackground(new java.awt.Color(204, 204, 204));
        jmiAccount.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiAccount.setForeground(new java.awt.Color(0, 0, 0));
        jmiAccount.setText("Tài khoản");
        jmiAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAccountActionPerformed(evt);
            }
        });
        jmManagerment.add(jmiAccount);

        jmiCustomer.setBackground(new java.awt.Color(204, 204, 204));
        jmiCustomer.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jmiCustomer.setText("Khách hàng");
        jmiCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCustomerActionPerformed(evt);
            }
        });
        jmManagerment.add(jmiCustomer);

        jmiProduct.setBackground(new java.awt.Color(204, 204, 204));
        jmiProduct.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiProduct.setForeground(new java.awt.Color(0, 0, 0));
        jmiProduct.setText("Hàng hóa");
        jmiProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductActionPerformed(evt);
            }
        });
        jmManagerment.add(jmiProduct);

        jmiPawnCoupon.setBackground(new java.awt.Color(204, 204, 204));
        jmiPawnCoupon.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiPawnCoupon.setForeground(new java.awt.Color(0, 0, 0));
        jmiPawnCoupon.setText("Hợp đồng");
        jmiPawnCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPawnCouponActionPerformed(evt);
            }
        });
        jmManagerment.add(jmiPawnCoupon);

        jHeaderMenuBar.add(jmManagerment);

        jmStatistic.setBackground(new java.awt.Color(153, 153, 153));
        jmStatistic.setForeground(new java.awt.Color(0, 0, 0));
        jmStatistic.setText("Thống kê");

        jmiStatistic.setBackground(new java.awt.Color(204, 204, 204));
        jmiStatistic.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jmiStatistic.setForeground(new java.awt.Color(0, 0, 0));
        jmiStatistic.setText("Thống kê");
        jmiStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStatisticActionPerformed(evt);
            }
        });
        jmStatistic.add(jmiStatistic);

        jHeaderMenuBar.add(jmStatistic);

        setJMenuBar(jHeaderMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAccountActionPerformed
        String title = "Tài khoản";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jaccounttab = new AccountJPanelForm();
            jtpHomePage.addTab(title, jaccounttab);
        }
        jtpHomePage.setSelectedComponent(jaccounttab);
    }//GEN-LAST:event_jmiAccountActionPerformed

    @SuppressWarnings("static-access")
    private void jmiLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOutActionPerformed
        if (MessageSupport.MessageConfirm("Đăng xuất", "Xác nhận đăng xuất?") == JOptionPane.YES_OPTION) {
            this.dispose();
            this.jfparrent.setVisible(true);
        }
    }//GEN-LAST:event_jmiLogOutActionPerformed

    private void jlblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProfileMouseClicked
        String title = "Thông tin tài khoản";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jprofiletab = new ProfileJPanelForm();
            jprofiletab.setName(title);
            
            jtpHomePage.addTab(title, jprofiletab);
        }
        jtpHomePage.setSelectedComponent(jprofiletab);
    }//GEN-LAST:event_jlblProfileMouseClicked

    private void jmiCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCustomerActionPerformed
        String title = "Khách hàng";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jcustomertab = new CustomerJPanelForm();
            jcustomertab.setName(title);
            
            jtpHomePage.addTab(title, jcustomertab);
        }
        jtpHomePage.setSelectedComponent(jcustomertab);
    }//GEN-LAST:event_jmiCustomerActionPerformed

    private void jmiProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductActionPerformed
        String title = "Hàng hóa";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jproducttab = new ProductJPanelForm();
            jproducttab.setName(title);
            
            jtpHomePage.addTab(title, jproducttab);
        }
        jtpHomePage.setSelectedComponent(jproducttab);
    }//GEN-LAST:event_jmiProductActionPerformed

    private void jmiPawnCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPawnCouponActionPerformed
        String title = "Hợp đồng";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jpawncoupontab = new PawnCouponJPanelForm();
            jpawncoupontab.setName(title);
            
            jtpHomePage.addTab(title, jpawncoupontab);
        }
        jtpHomePage.setSelectedComponent(jpawncoupontab);
    }//GEN-LAST:event_jmiPawnCouponActionPerformed

    private void jmiStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStatisticActionPerformed
        String title = "Thống kê";
        if (jtpHomePage.indexOfTab(title) == -1) {
            jstatistictab = new StatisticJPanelForm();
            jstatistictab.setName(title);
            
            jtpHomePage.addTab(title, jstatistictab);
        }
        jtpHomePage.setSelectedComponent(jstatistictab);
    }//GEN-LAST:event_jmiStatisticActionPerformed

    private void jlblProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProfileMouseMoved
        jAccountNamePanel.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jlblProfileMouseMoved

    private void jlblProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProfileMouseExited
        jAccountNamePanel.setBackground(jFooterPanel.getBackground());
    }//GEN-LAST:event_jlblProfileMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePageJFrameForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAccountNamePanel;
    private javax.swing.JPanel jFooterPanel;
    private javax.swing.JMenuBar jHeaderMenuBar;
    private javax.swing.JPanel jHomePagePanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbHomePage;
    public static javax.swing.JLabel jlbToday;
    public static javax.swing.JLabel jlblClock;
    public static javax.swing.JLabel jlblProfile;
    private javax.swing.JMenu jmManagerment;
    private javax.swing.JMenu jmStatistic;
    private javax.swing.JMenu jmSystem;
    private javax.swing.JMenuItem jmiAccount;
    private javax.swing.JMenuItem jmiCustomer;
    private javax.swing.JMenuItem jmiLogOut;
    private javax.swing.JMenuItem jmiPawnCoupon;
    private javax.swing.JMenuItem jmiProduct;
    private javax.swing.JMenuItem jmiStatistic;
    public static javax.swing.JTabbedPane jtpHomePage;
    // End of variables declaration//GEN-END:variables
}
