/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ActivityHistoryController;
import Model.ActivityHistory;
import Model.StaticUser;
import Support.MessageSupport;
import Support.Support;
import View.JTabbedPaneForm.AccountJPanelForm;
import View.JTabbedPaneForm.CustomerJPanelForm;
import View.JTabbedPaneForm.PawnCouponJPanelForm;
import View.JTabbedPaneForm.ProductJPanelForm;
import View.JTabbedPaneForm.ProfileJPanelForm;
import View.JTabbedPaneForm.StatisticJPanelForm;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NVS
 */
@SuppressWarnings("ClassWithoutLogger")
public class HomePageJFrameForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private static JFrame jfparrent = null;
    private JPanel jaccounttab = null;
    private JPanel jprofiletab = null;
    private JPanel jcustomertab = null;
    private JPanel jproducttab = null;
    private JPanel jpawncoupontab = null;
    private JPanel jstatistictab = null;

    public HomePageJFrameForm() {
        initComponents();
    }

    @SuppressWarnings({"static-access", "OverridableMethodCallInConstructor", "SleepWhileInLoop"})
    public HomePageJFrameForm(JFrame jfparrent) {
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                ActivityHistoryController.getCurrentInstance().insert(
                        new ActivityHistory(Support.dateToString(new Date(), Support.getDateTimeFormat()),
                                StaticUser.getCurrentInstance(), "Đăng xuất", "", ""));
            }
        });
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/logo.png")));
        this.jfparrent = jfparrent;
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (StaticUser.getCurrentInstance().getUsername().equals("admin")) {
            isAdmin(true);
        } else {
            isAdmin(false);
        }
        Support.ScaleImage(jlbHomePage, getClass().getResource("/Image/HomePage/HomePageImage0.png"));
        @SuppressWarnings("CollectionWithoutInitialCapacity")
        ArrayList<URL> imagesList = new ArrayList<>();
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage0.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage1.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage2.jpg"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage3.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage4.png"));
        imagesList.add(getClass().getResource("/Image/HomePage/HomePageImage5.jpg"));
        Support.setSlideImage(jlbHomePage, imagesList);

        Support.getClock(jlblClock, true);
        setProfileName(StaticUser.getCurrentInstance().getFullname());
    }

    public static void setProfileName(String fullname) {
        jlblProfile.setText(fullname + "     ");
    }

    public void isAdmin(boolean b) {
        jAccountMenuItem.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jHomePagePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlblProfile = new javax.swing.JLabel();
        jlblProfile1 = new javax.swing.JLabel();
        jlblClock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jHomePageTabbedPane = new javax.swing.JTabbedPane();
        jlbHomePage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jSystemMenu = new javax.swing.JMenu();
        jLogOutMenuItem = new javax.swing.JMenuItem();
        jManagermentMenu = new javax.swing.JMenu();
        jAccountMenuItem = new javax.swing.JMenuItem();
        jCustomerMenuItem = new javax.swing.JMenuItem();
        jProductMenuItem = new javax.swing.JMenuItem();
        jPawnCouponMenuItem = new javax.swing.JMenuItem();
        jStatisticMenu = new javax.swing.JMenu();
        jStatisticMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm quản lý cầm dùm đồ");
        setBackground(new java.awt.Color(102, 102, 102));

        jHomePagePanel.setBackground(new java.awt.Color(0, 255, 255));
        jHomePagePanel.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jlblProfile.setBackground(new java.awt.Color(204, 204, 204));
        jlblProfile.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jlblProfile.setForeground(new java.awt.Color(255, 0, 0));
        jlblProfile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblProfile.setText("Họ và tên     ");
        jlblProfile.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblProfileMouseClicked(evt);
            }
        });

        jlblProfile1.setBackground(new java.awt.Color(204, 204, 204));
        jlblProfile1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblProfile1.setForeground(new java.awt.Color(255, 0, 0));
        jlblProfile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblProfile1.setText("Hôm nay :");
        jlblProfile1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jlblClock.setBackground(new java.awt.Color(204, 204, 204));
        jlblClock.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jlblClock.setForeground(new java.awt.Color(255, 0, 0));
        jlblClock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblClock.setText("Clock");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jlblProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(jlblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblProfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHomePageTabbedPane.setBackground(new java.awt.Color(204, 204, 204));
        jHomePageTabbedPane.setForeground(new java.awt.Color(0, 0, 0));
        jHomePageTabbedPane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jHomePageTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));
        jPanel1.add(jlbHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 1270, 600));

        javax.swing.GroupLayout jHomePagePanelLayout = new javax.swing.GroupLayout(jHomePagePanel);
        jHomePagePanel.setLayout(jHomePagePanelLayout);
        jHomePagePanelLayout.setHorizontalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHomePagePanelLayout.setVerticalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePagePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jSystemMenu.setBackground(new java.awt.Color(153, 153, 153));
        jSystemMenu.setForeground(new java.awt.Color(0, 0, 0));
        jSystemMenu.setText("Hệ thống");

        jLogOutMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jLogOutMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLogOutMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jLogOutMenuItem.setText("Đăng xuất");
        jLogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutMenuItemActionPerformed(evt);
            }
        });
        jSystemMenu.add(jLogOutMenuItem);

        jMenuBar1.add(jSystemMenu);

        jManagermentMenu.setBackground(new java.awt.Color(153, 153, 153));
        jManagermentMenu.setForeground(new java.awt.Color(0, 0, 0));
        jManagermentMenu.setText("Quản lý");

        jAccountMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jAccountMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jAccountMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jAccountMenuItem.setText("Tài khoản");
        jAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccountMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jAccountMenuItem);

        jCustomerMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jCustomerMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jCustomerMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jCustomerMenuItem.setText("Khách hàng");
        jCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jCustomerMenuItem);

        jProductMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jProductMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jProductMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jProductMenuItem.setText("Hàng hóa");
        jProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jProductMenuItem);

        jPawnCouponMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jPawnCouponMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jPawnCouponMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jPawnCouponMenuItem.setText("Hợp đồng");
        jPawnCouponMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPawnCouponMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jPawnCouponMenuItem);

        jMenuBar1.add(jManagermentMenu);

        jStatisticMenu.setBackground(new java.awt.Color(153, 153, 153));
        jStatisticMenu.setForeground(new java.awt.Color(0, 0, 0));
        jStatisticMenu.setText("Thống kê");

        jStatisticMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jStatisticMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jStatisticMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jStatisticMenuItem.setText("Thống kê");
        jStatisticMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatisticMenuItemActionPerformed(evt);
            }
        });
        jStatisticMenu.add(jStatisticMenuItem);

        jMenuBar1.add(jStatisticMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccountMenuItemActionPerformed
        String title = "Tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jaccounttab = new AccountJPanelForm();
            jHomePageTabbedPane.addTab(title, jaccounttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jaccounttab);
    }//GEN-LAST:event_jAccountMenuItemActionPerformed

    @SuppressWarnings("static-access")
    private void jLogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutMenuItemActionPerformed
        if (MessageSupport.MessageConfirm("Đăng xuất", "Xác nhận đăng xuất?") == JOptionPane.YES_OPTION) {
            this.dispose();
            this.jfparrent.setVisible(true);
        }
    }//GEN-LAST:event_jLogOutMenuItemActionPerformed

    private void jlblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProfileMouseClicked
        String title = "Thông tin tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jprofiletab = new ProfileJPanelForm();
            jHomePageTabbedPane.addTab(title, jprofiletab);
        }
        jHomePageTabbedPane.setSelectedComponent(jprofiletab);
    }//GEN-LAST:event_jlblProfileMouseClicked

    private void jCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerMenuItemActionPerformed
        String title = "Khách hàng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jcustomertab = new CustomerJPanelForm();
            jHomePageTabbedPane.addTab(title, jcustomertab);
        }
        jHomePageTabbedPane.setSelectedComponent(jcustomertab);
    }//GEN-LAST:event_jCustomerMenuItemActionPerformed

    private void jProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductMenuItemActionPerformed
        String title = "Hàng hóa";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jproducttab = new ProductJPanelForm();
            jHomePageTabbedPane.addTab(title, jproducttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jproducttab);
    }//GEN-LAST:event_jProductMenuItemActionPerformed

    private void jPawnCouponMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPawnCouponMenuItemActionPerformed
        String title = "Hợp đồng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jpawncoupontab = new PawnCouponJPanelForm();
            jHomePageTabbedPane.addTab(title, jpawncoupontab);
        }
        jHomePageTabbedPane.setSelectedComponent(jpawncoupontab);
    }//GEN-LAST:event_jPawnCouponMenuItemActionPerformed

    private void jStatisticMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatisticMenuItemActionPerformed
        String title = "Thống kê";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jstatistictab = new StatisticJPanelForm();
            jHomePageTabbedPane.addTab(title, jstatistictab);
        }
        jHomePageTabbedPane.setSelectedComponent(jstatistictab);
    }//GEN-LAST:event_jStatisticMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePageJFrameForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAccountMenuItem;
    private javax.swing.JMenuItem jCustomerMenuItem;
    private javax.swing.JPanel jHomePagePanel;
    public static javax.swing.JTabbedPane jHomePageTabbedPane;
    private javax.swing.JMenuItem jLogOutMenuItem;
    private javax.swing.JMenu jManagermentMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jPawnCouponMenuItem;
    private javax.swing.JMenuItem jProductMenuItem;
    private javax.swing.JMenu jStatisticMenu;
    private javax.swing.JMenuItem jStatisticMenuItem;
    private javax.swing.JMenu jSystemMenu;
    private javax.swing.JLabel jlbHomePage;
    public static javax.swing.JLabel jlblClock;
    public static javax.swing.JLabel jlblProfile;
    public static javax.swing.JLabel jlblProfile1;
    // End of variables declaration//GEN-END:variables
}
