/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.*;
import View.JTabbedPaneForm.JAccountPanelForm;
import javax.swing.JFrame;
import Support.*;
import View.JTabbedPaneForm.JCustomerPanelForm;
import View.JTabbedPaneForm.JPawnCouponPanelForm;
import View.JTabbedPaneForm.JProductPanelForm;
import View.JTabbedPaneForm.JProfilePanelForm;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NVS
 */
public class JHomePageForm extends javax.swing.JFrame {

    private static JFrame jfparrent = null;

    private JPanel jaccounttab = null;
    private JPanel jprofiletab = null;
    private JPanel jcustomertab = null;
    private JPanel jproducttab = null;
    private JPanel jpawncoupontab = null;

    public JHomePageForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setProfileName();
    }

    public JHomePageForm(JFrame jfparrent) {
        initComponents();
        this.jfparrent = jfparrent;
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setProfileName();
    }

    public void setProfileName() {
        jlbProfile.setText(User.getCurrentInstance().getFullname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jHomePageTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jlbProfile = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jSystemMenu = new javax.swing.JMenu();
        jLogOutMenuItem = new javax.swing.JMenuItem();
        jManagermentMenu = new javax.swing.JMenu();
        jAccountMenuItem = new javax.swing.JMenuItem();
        jCustomerMenuItem = new javax.swing.JMenuItem();
        jProductMenuItem = new javax.swing.JMenuItem();
        jPawnCouponMenuItem = new javax.swing.JMenuItem();
        jReportMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm quản lý cầm dùm đồ");

        jlbProfile.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jlbProfile.setForeground(new java.awt.Color(255, 0, 0));
        jlbProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbProfile.setText("Họ và tên");
        jlbProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(798, Short.MAX_VALUE)
                .addComponent(jlbProfile)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jHomePageTabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jHomePageTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSystemMenu.setText("Hệ thống");

        jLogOutMenuItem.setText("Đăng xuất");
        jLogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutMenuItemActionPerformed(evt);
            }
        });
        jSystemMenu.add(jLogOutMenuItem);

        jMenuBar1.add(jSystemMenu);

        jManagermentMenu.setText("Quản lý");

        jAccountMenuItem.setText("Tài khoản");
        jAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccountMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jAccountMenuItem);

        jCustomerMenuItem.setText("Khách hàng");
        jCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jCustomerMenuItem);

        jProductMenuItem.setText("Hàng hóa");
        jProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jProductMenuItem);

        jPawnCouponMenuItem.setText("Hợp đồng");
        jPawnCouponMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPawnCouponMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jPawnCouponMenuItem);

        jMenuBar1.add(jManagermentMenu);

        jReportMenu.setText("Thống kê");
        jMenuBar1.add(jReportMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccountMenuItemActionPerformed
        String title = "Tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jaccounttab = new JAccountPanelForm();
            jHomePageTabbedPane.addTab(title, jaccounttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jaccounttab);
    }//GEN-LAST:event_jAccountMenuItemActionPerformed

    private void jLogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutMenuItemActionPerformed
        if (MessageSupport.Confirm(null, "Đăng xuất", "Xác nhận đăng xuất?") == JOptionPane.YES_OPTION) {
            this.dispose();
            this.jfparrent.setVisible(true);
        }
    }//GEN-LAST:event_jLogOutMenuItemActionPerformed

    private void jlbProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbProfileMouseClicked
        String title = "Thông tin tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jprofiletab = new JProfilePanelForm();
            jHomePageTabbedPane.addTab(title, jprofiletab);
        }
        jHomePageTabbedPane.setSelectedComponent(jprofiletab);
    }//GEN-LAST:event_jlbProfileMouseClicked

    private void jCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerMenuItemActionPerformed
        String title = "Khách hàng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jcustomertab = new JCustomerPanelForm();
            jHomePageTabbedPane.addTab(title, jcustomertab);
        }
        jHomePageTabbedPane.setSelectedComponent(jcustomertab);
    }//GEN-LAST:event_jCustomerMenuItemActionPerformed

    private void jProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductMenuItemActionPerformed
        String title = "Hàng hóa";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jproducttab = new JProductPanelForm();
            jHomePageTabbedPane.addTab(title, jproducttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jproducttab);
    }//GEN-LAST:event_jProductMenuItemActionPerformed

    private void jPawnCouponMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPawnCouponMenuItemActionPerformed
        String title = "Hợp đồng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jpawncoupontab = new JPawnCouponPanelForm();
            jHomePageTabbedPane.addTab(title, jpawncoupontab);
        }
        jHomePageTabbedPane.setSelectedComponent(jpawncoupontab);
    }//GEN-LAST:event_jPawnCouponMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHomePageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAccountMenuItem;
    private javax.swing.JMenuItem jCustomerMenuItem;
    private javax.swing.JTabbedPane jHomePageTabbedPane;
    private javax.swing.JMenuItem jLogOutMenuItem;
    private javax.swing.JMenu jManagermentMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jPawnCouponMenuItem;
    private javax.swing.JMenuItem jProductMenuItem;
    private javax.swing.JMenu jReportMenu;
    private javax.swing.JMenu jSystemMenu;
    public static javax.swing.JLabel jlbProfile;
    // End of variables declaration//GEN-END:variables
}
