/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.*;
import View.JTabbedPaneForm.JAccountPanelForm;
import javax.swing.JFrame;
import Support.*;
import View.JTabbedPaneForm.JActivityHistoryPanelForm;
import View.JTabbedPaneForm.JCustomerPanelForm;
import View.JTabbedPaneForm.JPawnCouponPanelForm;
import View.JTabbedPaneForm.JProductPanelForm;
import View.JTabbedPaneForm.JProfilePanelForm;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NVS
 */
public class JHomePageForm extends javax.swing.JFrame {

    private static JFrame jfparrent = null;
    private JPanel jaccounttab = null;
    private JPanel jprofiletab = null;
    private JPanel jcustomertab = null;
    private JPanel jproducttab = null;
    private JPanel jpawncoupontab = null;
    private JPanel jactivehistorytab = null;
    
    public JHomePageForm() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/logo.png")));
        Support.ScaleImage(jHomePagePanel, getClass().getResource("/Image/HomePageImage.png"));
        this.jfparrent = jfparrent;
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setProfileName(User.getCurrentInstance().getUsername());
        Support.getClock(jlblClock,true);
        if (CheckSupport.equals(User.getCurrentInstance().getUsername(), "admin")) {
            isAdmin(true);
        }else{
            isAdmin(false);
        }
    }
    
    public JHomePageForm(JFrame jfparrent) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/logo.png")));
        this.jfparrent = jfparrent;
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setProfileName(User.getCurrentInstance().getFullname());
        Support.getClock(jlblClock,true);
        if (CheckSupport.equals(User.getCurrentInstance().getUsername(), "admin")) {
            isAdmin(true);
        }else{
            isAdmin(false);
        }
    }

    public static void setProfileName(String fullname) {
        jlblProfile.setText(fullname);
    }
    
    
    public void isAdmin(boolean b){
        jAccountMenuItem.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHomePagePanel = new javax.swing.JPanel();
        jHomePageTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jlblProfile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblClock = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jSystemMenu = new javax.swing.JMenu();
        jLogOutMenuItem = new javax.swing.JMenuItem();
        jActiveHistoryMenuItem = new javax.swing.JMenuItem();
        jManagermentMenu = new javax.swing.JMenu();
        jAccountMenuItem = new javax.swing.JMenuItem();
        jCustomerMenuItem = new javax.swing.JMenuItem();
        jProductMenuItem = new javax.swing.JMenuItem();
        jPawnCouponMenuItem = new javax.swing.JMenuItem();
        jReportMenuItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm quản lý cầm dùm đồ");
        setBackground(new java.awt.Color(102, 102, 102));

        jHomePagePanel.setBackground(new java.awt.Color(204, 204, 204));
        jHomePagePanel.setForeground(new java.awt.Color(255, 255, 255));

        jHomePageTabbedPane.setBackground(new java.awt.Color(204, 204, 204));
        jHomePageTabbedPane.setForeground(new java.awt.Color(0, 0, 0));
        jHomePageTabbedPane.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jlblProfile.setBackground(new java.awt.Color(204, 204, 204));
        jlblProfile.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jlblProfile.setForeground(new java.awt.Color(255, 0, 0));
        jlblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblProfile.setText("Họ và tên");
        jlblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblProfileMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hôm nay:      ");

        jlblClock.setBackground(new java.awt.Color(204, 204, 204));
        jlblClock.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jlblClock.setForeground(new java.awt.Color(255, 0, 0));
        jlblClock.setText("Clock");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblClock, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jlblProfile)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jHomePagePanelLayout = new javax.swing.GroupLayout(jHomePagePanel);
        jHomePagePanel.setLayout(jHomePagePanelLayout);
        jHomePagePanelLayout.setHorizontalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jHomePageTabbedPane)
        );
        jHomePagePanelLayout.setVerticalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePagePanelLayout.createSequentialGroup()
                .addComponent(jHomePageTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jSystemMenu.setBackground(new java.awt.Color(204, 204, 204));
        jSystemMenu.setForeground(new java.awt.Color(0, 0, 0));
        jSystemMenu.setText("Hệ thống");

        jLogOutMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jLogOutMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLogOutMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jLogOutMenuItem.setText("Đăng xuất");
        jLogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutMenuItemActionPerformed(evt);
            }
        });
        jSystemMenu.add(jLogOutMenuItem);

        jActiveHistoryMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jActiveHistoryMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jActiveHistoryMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jActiveHistoryMenuItem.setText("Lịch sử hoạt động");
        jActiveHistoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActiveHistoryMenuItemActionPerformed(evt);
            }
        });
        jSystemMenu.add(jActiveHistoryMenuItem);

        jMenuBar1.add(jSystemMenu);

        jManagermentMenu.setBackground(new java.awt.Color(204, 204, 204));
        jManagermentMenu.setForeground(new java.awt.Color(0, 0, 0));
        jManagermentMenu.setText("Quản lý");

        jAccountMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jAccountMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jAccountMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jAccountMenuItem.setText("Tài khoản");
        jAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccountMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jAccountMenuItem);

        jCustomerMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jCustomerMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCustomerMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jCustomerMenuItem.setText("Khách hàng");
        jCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jCustomerMenuItem);

        jProductMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jProductMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jProductMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jProductMenuItem.setText("Hàng hóa");
        jProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jProductMenuItem);

        jPawnCouponMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        jPawnCouponMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jPawnCouponMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jPawnCouponMenuItem.setText("Hợp đồng");
        jPawnCouponMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPawnCouponMenuItemActionPerformed(evt);
            }
        });
        jManagermentMenu.add(jPawnCouponMenuItem);

        jMenuBar1.add(jManagermentMenu);

        jReportMenuItem.setBackground(new java.awt.Color(204, 204, 204));
        jReportMenuItem.setForeground(new java.awt.Color(0, 0, 0));
        jReportMenuItem.setText("Thống kê");
        jMenuBar1.add(jReportMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccountMenuItemActionPerformed
        String title = "Tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jaccounttab = new JAccountPanelForm();
            jHomePageTabbedPane.addTab(title, jaccounttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jaccounttab);
    }//GEN-LAST:event_jAccountMenuItemActionPerformed

    private void jLogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutMenuItemActionPerformed
        if (MessageSupport.Confirm(null, "Đăng xuất", "Xác nhận đăng xuất?") == JOptionPane.YES_OPTION) {
            this.dispose();
            this.jfparrent.setVisible(true);
            JLoginForm.setDefaultPassword();
        }
    }//GEN-LAST:event_jLogOutMenuItemActionPerformed

    private void jlblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProfileMouseClicked
        String title = "Thông tin tài khoản";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jprofiletab = new JProfilePanelForm();
            jHomePageTabbedPane.addTab(title, jprofiletab);
        }
        jHomePageTabbedPane.setSelectedComponent(jprofiletab);
    }//GEN-LAST:event_jlblProfileMouseClicked

    private void jCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerMenuItemActionPerformed
        String title = "Khách hàng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jcustomertab = new JCustomerPanelForm();
            jHomePageTabbedPane.addTab(title, jcustomertab);
        }
        jHomePageTabbedPane.setSelectedComponent(jcustomertab);
    }//GEN-LAST:event_jCustomerMenuItemActionPerformed

    private void jProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductMenuItemActionPerformed
        String title = "Hàng hóa";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jproducttab = new JProductPanelForm();
            jHomePageTabbedPane.addTab(title, jproducttab);
        }
        jHomePageTabbedPane.setSelectedComponent(jproducttab);
    }//GEN-LAST:event_jProductMenuItemActionPerformed

    private void jPawnCouponMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPawnCouponMenuItemActionPerformed
        String title = "Hợp đồng";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jpawncoupontab = new JPawnCouponPanelForm();
            jHomePageTabbedPane.addTab(title, jpawncoupontab);
        }
        jHomePageTabbedPane.setSelectedComponent(jpawncoupontab);
    }//GEN-LAST:event_jPawnCouponMenuItemActionPerformed

    private void jActiveHistoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActiveHistoryMenuItemActionPerformed
        String title = "Lịch sử hoạt động";
        if (jHomePageTabbedPane.indexOfTab(title) == -1) {
            jactivehistorytab = new JActivityHistoryPanelForm();
            jHomePageTabbedPane.addTab(title, jactivehistorytab);
        }
        jHomePageTabbedPane.setSelectedComponent(jactivehistorytab);
    }//GEN-LAST:event_jActiveHistoryMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHomePageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAccountMenuItem;
    private javax.swing.JMenuItem jActiveHistoryMenuItem;
    private javax.swing.JMenuItem jCustomerMenuItem;
    private javax.swing.JPanel jHomePagePanel;
    private javax.swing.JTabbedPane jHomePageTabbedPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jLogOutMenuItem;
    private javax.swing.JMenu jManagermentMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jPawnCouponMenuItem;
    private javax.swing.JMenuItem jProductMenuItem;
    private javax.swing.JMenu jReportMenuItem;
    private javax.swing.JMenu jSystemMenu;
    private javax.swing.JLabel jlblClock;
    public static javax.swing.JLabel jlblProfile;
    // End of variables declaration//GEN-END:variables
}
