/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PawnCouponController;
import Model.PawnCoupon;
import Support.Support;

/**
 *
 * @author NVS
 */
@SuppressWarnings("ClassWithoutLogger")
public class PawnCouponPageBerJFrameForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form PawnCouponPageBer
     *
     * @param pawnCoupon
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public PawnCouponPageBerJFrameForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Support.ScaleImage(jlbLogo, getClass().getResource("/Image/logo.png"));
        Support.ScaleImage(jlbPrint, getClass().getResource("/Image/printImage.jpg"));
    }

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public PawnCouponPageBerJFrameForm(PawnCoupon pawnCoupon) {
        initComponents();
        this.setLocationRelativeTo(null);
        Support.ScaleImage(jlbLogo, getClass().getResource("/Image/logo.png"));
        Support.ScaleImage(jlbPrint, getClass().getResource("/Image/printImage.jpg"));
        setPawnCouponPageber(pawnCoupon);
    }

    private void setPawnCouponPageber(PawnCoupon pawnCoupon) {
        jlbPawnCouponID.setText(pawnCoupon.getId());
        jlbCustomerName.setText(pawnCoupon.getCustomer().getFullname());
        jlbCustomerAddress.setText(pawnCoupon.getCustomer().getAddress());
        jlbCustomerID.setText(pawnCoupon.getCustomer().getId());
        jlbProductName.setText(pawnCoupon.getProduct().getName());
        jlbProductInformation.setText(pawnCoupon.getProduct().getInfo());
        jlbPawnCouponPriceInNumber.setText(Support.getFormatNumber(pawnCoupon.getPrice()));
        jlbPawnCouponPriceInText.setText(Support.getTextNumber(pawnCoupon.getPrice()));
        jlbPawnCouponInterestRate.setText(String.valueOf(pawnCoupon.getInterestRate()));
        jlbPawnCouponInterest.setText(Support.getFormatNumber(Math.round(pawnCoupon.getPrice() * pawnCoupon.getInterestRate() / 100)));
        jlbPawnDate.setText(pawnCoupon.getPawnDate());
        jlbTheNextPaymentDate.setText(PawnCouponController.getCurrentInstance().getTheNextPaymentDate(pawnCoupon));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPawnCouponPageberJPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbLogo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlbPawnCouponID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlbCustomerName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlbCustomerAddress = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlbCustomerID = new javax.swing.JLabel();
        jlbCustomerAddress2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlbPawnCouponPriceInNumber = new javax.swing.JLabel();
        jlbPawnCouponPriceInNumber1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jlbPawnCouponPriceInText = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate = new javax.swing.JLabel();
        jlbPawnCouponInterestRate1 = new javax.swing.JLabel();
        jlbPawnDate = new javax.swing.JLabel();
        jlbPawnCouponInterestRate2 = new javax.swing.JLabel();
        jlbTheNextPaymentDate = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jlbPawnCouponInterest = new javax.swing.JLabel();
        jlbPawnCouponPriceInNumber2 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate3 = new javax.swing.JLabel();
        jlbCustomerAddress3 = new javax.swing.JLabel();
        jlbProductName = new javax.swing.JLabel();
        jlbCustomerAddress5 = new javax.swing.JLabel();
        jlbProductInformation = new javax.swing.JLabel();
        jlbPawnCouponPriceInNumber3 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate7 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate5 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate6 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate8 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate9 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate11 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate13 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate14 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate15 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate17 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate18 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate19 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate10 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate12 = new javax.swing.JLabel();
        jlbPawnCouponInterestRate20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbPrint = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPawnCouponPageberJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dịch vụ cầm dùm đồ");
        jLabel3.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CÒN THỞ  CÒN GỠ");
        jLabel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("STK: 040081697886");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("NH: Sacombank");
        jLabel5.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Độc lập - Tự do - Hạnh phúc");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jlbLogo.setBackground(new java.awt.Color(153, 153, 153));
        jlbLogo.setForeground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(".................................., ngày............tháng............năm 202.....         ");
        jLabel11.setToolTipText("");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("~~~~~~~~~~~~~~~~o0o~~~~~~~~~~~~~~~~");
        jLabel12.setToolTipText("");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("SĐT: 0917672477");
        jLabel10.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Đ/C: 26 đường số 34, Linh Đông, Thủ Đức");
        jLabel13.setToolTipText("");

        jlbPawnCouponID.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jlbPawnCouponID.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPawnCouponID.setText("...........................");
        jlbPawnCouponID.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Số hợp đồng: ");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Chủ TK: Nguyễn Văn Sĩ");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponID))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jlbPawnCouponID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("HỢP ĐỒNG CẦM CỐ TÀI SẢN");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Họ và tên ông(bà) :");
        jLabel6.setToolTipText("");

        jlbCustomerName.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbCustomerName.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerName.setText(".......................................................................................................................................................");
        jlbCustomerName.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("đại diện đến cầm đồ");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Địa chỉ :");
        jLabel19.setToolTipText("");

        jlbCustomerAddress.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbCustomerAddress.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerAddress.setText("..................................................................................................................................................................");
        jlbCustomerAddress.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("CMND/CCCD : ");
        jLabel20.setToolTipText("");

        jlbCustomerID.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbCustomerID.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerID.setText("..................................................................................................................................................................");
        jlbCustomerID.setToolTipText("");

        jlbCustomerAddress2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbCustomerAddress2.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerAddress2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerAddress2.setText("Tôi xin thỏa thuận tự nguyện đặt đồ vật, tài sản với những điều kiện kê sau đây: ");
        jlbCustomerAddress2.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Số tiền cầm bằng số : ");
        jLabel21.setToolTipText("");

        jlbPawnCouponPriceInNumber.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnCouponPriceInNumber.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponPriceInNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponPriceInNumber.setText("....................................");
        jlbPawnCouponPriceInNumber.setToolTipText("");

        jlbPawnCouponPriceInNumber1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponPriceInNumber1.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponPriceInNumber1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponPriceInNumber1.setText("(VND)");
        jlbPawnCouponPriceInNumber1.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Số tiền cầm bằng chữ: ");
        jLabel23.setToolTipText("");

        jlbPawnCouponPriceInText.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnCouponPriceInText.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponPriceInText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponPriceInText.setText(".......................................................................");
        jlbPawnCouponPriceInText.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Lãi suất : ");
        jLabel22.setToolTipText("");

        jlbPawnCouponInterestRate.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnCouponInterestRate.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate.setText("...................................................");
        jlbPawnCouponInterestRate.setToolTipText("");

        jlbPawnCouponInterestRate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate1.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate1.setText("Từ ngày :");
        jlbPawnCouponInterestRate1.setToolTipText("");

        jlbPawnDate.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnDate.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnDate.setText("..................................................");
        jlbPawnDate.setToolTipText("");

        jlbPawnCouponInterestRate2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate2.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate2.setText("Đến ngày :");
        jlbPawnCouponInterestRate2.setToolTipText("");

        jlbTheNextPaymentDate.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbTheNextPaymentDate.setForeground(new java.awt.Color(0, 0, 0));
        jlbTheNextPaymentDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbTheNextPaymentDate.setText("..........................................................");
        jlbTheNextPaymentDate.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Lãi: ");
        jLabel26.setToolTipText("");

        jlbPawnCouponInterest.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnCouponInterest.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterest.setText("..........................................................");
        jlbPawnCouponInterest.setToolTipText("");

        jlbPawnCouponPriceInNumber2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponPriceInNumber2.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponPriceInNumber2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponPriceInNumber2.setText("(VND)");
        jlbPawnCouponPriceInNumber2.setToolTipText("");

        jlbPawnCouponInterestRate3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbPawnCouponInterestRate3.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbPawnCouponInterestRate3.setText("Người cầm cố ");
        jlbPawnCouponInterestRate3.setToolTipText("");

        jlbCustomerAddress3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbCustomerAddress3.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerAddress3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerAddress3.setText("     - Tên tài sản : ");
        jlbCustomerAddress3.setToolTipText("");

        jlbProductName.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbProductName.setForeground(new java.awt.Color(0, 0, 0));
        jlbProductName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbProductName.setText(".....................................................................................................................................................");
        jlbProductName.setToolTipText("");

        jlbCustomerAddress5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbCustomerAddress5.setForeground(new java.awt.Color(0, 0, 0));
        jlbCustomerAddress5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCustomerAddress5.setText("     - Thông tin chi tiết : ");
        jlbCustomerAddress5.setToolTipText("");

        jlbProductInformation.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbProductInformation.setForeground(new java.awt.Color(0, 0, 0));
        jlbProductInformation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbProductInformation.setText("..................................................................................................................................................................");
        jlbProductInformation.setToolTipText("");

        jlbPawnCouponPriceInNumber3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponPriceInNumber3.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponPriceInNumber3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponPriceInNumber3.setText("(VND)");
        jlbPawnCouponPriceInNumber3.setToolTipText("");

        jlbPawnCouponInterestRate7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jlbPawnCouponInterestRate7.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate7.setText("(%/ngày)");
        jlbPawnCouponInterestRate7.setToolTipText("");

        jlbPawnCouponInterestRate5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate5.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate5.setText("     Hiệu cầm đồ được quyền quản lý, điều động khi cần thiết, khi hết hạn mà không có tiền chuộc lại, tôi đồng ý  bán");
        jlbPawnCouponInterestRate5.setToolTipText("");

        jlbPawnCouponInterestRate6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate6.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate6.setText(" đồ vật cầm ngang bằng số tiền tôi đã nhận của cửa hàng. ");
        jlbPawnCouponInterestRate6.setToolTipText("");

        jlbPawnCouponInterestRate8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate8.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPawnCouponInterestRate8.setToolTipText("");

        jlbPawnCouponInterestRate9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate9.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate9.setText("     Cửa hàng có quyền bán (Thu hồi vốn):   lời thì cửa hàng hưởng,  lỗ thì cửa hàng chịu.");
        jlbPawnCouponInterestRate9.setToolTipText("");

        jlbPawnCouponInterestRate11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate11.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPawnCouponInterestRate11.setToolTipText("");

        jlbPawnCouponInterestRate13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate13.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate13.setText("     Tôi không hề thắc mắc, khiếu nại, nhờ cậy ai.");
        jlbPawnCouponInterestRate13.setToolTipText("");

        jlbPawnCouponInterestRate14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate14.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate14.setText("      Số tài sản tôi mang cầm chính là của tôi. Quyền định đoạt cao nhất là tôi, số tài sản này không tranh chấp hoặc  ");
        jlbPawnCouponInterestRate14.setToolTipText("");

        jlbPawnCouponInterestRate15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate15.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate15.setText("cầm cố bất kỳ cá nhân nào.");
        jlbPawnCouponInterestRate15.setToolTipText("");

        jlbPawnCouponInterestRate16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate16.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate16.setText("     Nếu có điều gì gian trá, tôi xin chịu trách nhiệm trước Pháp luật Nhà nước.");
        jlbPawnCouponInterestRate16.setToolTipText("");

        jlbPawnCouponInterestRate17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate17.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate17.setText("     Bên hiệu cầm đồ có nghĩa vụ bảo quản tài sản cầm cố cho đến ngày thỏa thuận chuộc. Nếu tài sản của tôi hư hại");
        jlbPawnCouponInterestRate17.setToolTipText("");

        jlbPawnCouponInterestRate18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate18.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate18.setText("hay có bất kỳ dấu hiệu nào bất thường khác với lúc tôi cầm thì bên cửa hiệu phải bồi thường sản phẩm mới hoặc với");
        jlbPawnCouponInterestRate18.setToolTipText("");

        jlbPawnCouponInterestRate19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate19.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate19.setText("số tiền tương đương với giá trị tài sản theo thị trường.");
        jlbPawnCouponInterestRate19.setToolTipText("");

        jlbPawnCouponInterestRate10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate10.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate10.setText("(Ký và ghi rõ họ tên)");
        jlbPawnCouponInterestRate10.setToolTipText("");

        jlbPawnCouponInterestRate12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbPawnCouponInterestRate12.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbPawnCouponInterestRate12.setText("Đại diện cửa hàng");
        jlbPawnCouponInterestRate12.setToolTipText("");

        jlbPawnCouponInterestRate20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbPawnCouponInterestRate20.setForeground(new java.awt.Color(0, 0, 0));
        jlbPawnCouponInterestRate20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPawnCouponInterestRate20.setText("(Ký và ghi rõ họ tên)");
        jlbPawnCouponInterestRate20.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbCustomerAddress5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCustomerAddress3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbProductInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbPawnCouponInterestRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbPawnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jlbPawnCouponPriceInNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbPawnCouponPriceInNumber3))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jlbPawnCouponInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbPawnCouponInterestRate7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbPawnCouponPriceInText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jlbPawnCouponInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbPawnCouponPriceInNumber1))
                                            .addComponent(jlbTheNextPaymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbPawnCouponPriceInNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jlbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jlbCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jlbCustomerAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlbCustomerAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPawnCouponInterestRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPawnCouponInterestRate6, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbPawnCouponInterestRate9, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jlbPawnCouponInterestRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbPawnCouponInterestRate10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlbPawnCouponInterestRate12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbPawnCouponInterestRate20, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jlbPawnCouponInterestRate13, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate14, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate15, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate16, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate17, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate18, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbPawnCouponInterestRate19, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbPawnCouponInterestRate11, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate8, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jlbCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jlbCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbCustomerAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCustomerAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCustomerAddress5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbProductInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jlbPawnCouponPriceInNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jlbPawnCouponPriceInNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jlbPawnCouponInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPawnCouponInterestRate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPawnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jlbPawnCouponPriceInText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPawnCouponPriceInNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(jlbPawnCouponInterestRate7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbPawnCouponInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbPawnCouponPriceInNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTheNextPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPawnCouponInterestRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPawnCouponInterestRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPawnCouponInterestRate6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlbPawnCouponInterestRate8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlbPawnCouponInterestRate9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jlbPawnCouponInterestRate11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPawnCouponInterestRate19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbPawnCouponInterestRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbPawnCouponInterestRate10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbPawnCouponInterestRate12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbPawnCouponInterestRate20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );

        javax.swing.GroupLayout jPawnCouponPageberJPanelLayout = new javax.swing.GroupLayout(jPawnCouponPageberJPanel);
        jPawnCouponPageberJPanel.setLayout(jPawnCouponPageberJPanelLayout);
        jPawnCouponPageberJPanelLayout.setHorizontalGroup(
            jPawnCouponPageberJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPawnCouponPageberJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPawnCouponPageberJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPawnCouponPageberJPanelLayout.setVerticalGroup(
            jPawnCouponPageberJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPawnCouponPageberJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jlbPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPrintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlbPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlbPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPawnCouponPageberJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPawnCouponPageberJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPrintMouseClicked
        jPawnCouponPageberJPanel.print(null);
    }//GEN-LAST:event_jlbPrintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PawnCouponPageBerJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PawnCouponPageBerJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PawnCouponPageBerJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PawnCouponPageBerJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PawnCouponPageBerJFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPawnCouponPageberJPanel;
    private javax.swing.JLabel jlbCustomerAddress;
    private javax.swing.JLabel jlbCustomerAddress2;
    private javax.swing.JLabel jlbCustomerAddress3;
    private javax.swing.JLabel jlbCustomerAddress5;
    private javax.swing.JLabel jlbCustomerID;
    private javax.swing.JLabel jlbCustomerName;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JLabel jlbPawnCouponID;
    private javax.swing.JLabel jlbPawnCouponInterest;
    private javax.swing.JLabel jlbPawnCouponInterestRate;
    private javax.swing.JLabel jlbPawnCouponInterestRate1;
    private javax.swing.JLabel jlbPawnCouponInterestRate10;
    private javax.swing.JLabel jlbPawnCouponInterestRate11;
    private javax.swing.JLabel jlbPawnCouponInterestRate12;
    private javax.swing.JLabel jlbPawnCouponInterestRate13;
    private javax.swing.JLabel jlbPawnCouponInterestRate14;
    private javax.swing.JLabel jlbPawnCouponInterestRate15;
    private javax.swing.JLabel jlbPawnCouponInterestRate16;
    private javax.swing.JLabel jlbPawnCouponInterestRate17;
    private javax.swing.JLabel jlbPawnCouponInterestRate18;
    private javax.swing.JLabel jlbPawnCouponInterestRate19;
    private javax.swing.JLabel jlbPawnCouponInterestRate2;
    private javax.swing.JLabel jlbPawnCouponInterestRate20;
    private javax.swing.JLabel jlbPawnCouponInterestRate3;
    private javax.swing.JLabel jlbPawnCouponInterestRate5;
    private javax.swing.JLabel jlbPawnCouponInterestRate6;
    private javax.swing.JLabel jlbPawnCouponInterestRate7;
    private javax.swing.JLabel jlbPawnCouponInterestRate8;
    private javax.swing.JLabel jlbPawnCouponInterestRate9;
    private javax.swing.JLabel jlbPawnCouponPriceInNumber;
    private javax.swing.JLabel jlbPawnCouponPriceInNumber1;
    private javax.swing.JLabel jlbPawnCouponPriceInNumber2;
    private javax.swing.JLabel jlbPawnCouponPriceInNumber3;
    private javax.swing.JLabel jlbPawnCouponPriceInText;
    private javax.swing.JLabel jlbPawnDate;
    private javax.swing.JLabel jlbPrint;
    private javax.swing.JLabel jlbProductInformation;
    private javax.swing.JLabel jlbProductName;
    private javax.swing.JLabel jlbTheNextPaymentDate;
    // End of variables declaration//GEN-END:variables
}
